-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 13:26:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`All_stories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`All_stories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`All_stories` (
  `ID` INT NOT NULL,
  `Title_of_a_story` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Title_of_a_story`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Main_heroes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Main_heroes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Main_heroes` (
  `ID` INT NOT NULL,
  `MHName` VARCHAR(20) NOT NULL,
  `Sex` VARCHAR(10) NOT NULL,
  `Race` VARCHAR(50) NOT NULL,
  `Quote` VARCHAR(200) NULL,
  PRIMARY KEY (`MHName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Side_heroes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Side_heroes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Side_heroes` (
  `ID` INT NOT NULL,
  `SHName` VARCHAR(20) NOT NULL,
  `Sex` VARCHAR(10) NOT NULL,
  `Race` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`SHName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Main_Series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Main_Series` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Main_Series` (
  `ID` INT NOT NULL,
  `Title_of_a_main_series` VARCHAR(50) NOT NULL,
  `Magical_or_not` VARCHAR(5) NOT NULL,
  `For_children_or_not` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Title_of_a_main_series`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Side_Series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Side_Series` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Side_Series` (
  `ID` INT NOT NULL,
  `Title_of_a_side_series` VARCHAR(45) NOT NULL,
  `Real_world_or_not` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Title_of_a_side_series`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Places`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Places` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Places` (
  `ID` INT NOT NULL,
  `PName` VARCHAR(20) NOT NULL,
  `Climate` VARCHAR(20) NOT NULL,
  `Population` INT NOT NULL,
  `Political_system` VARCHAR(20) NULL,
  PRIMARY KEY (`PName`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Short_stories`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `mydb`.`Short_stories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Short_stories` (
  `ID` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Year` INT NOT NULL,
  `Main_hero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Title_of_a_story_idx` (`Title` ASC) VISIBLE,
  INDEX `MHName_idx` (`Main_hero` ASC) VISIBLE,
  CONSTRAINT `Title_of_a_short_story`
    FOREIGN KEY (`Title`)
    REFERENCES `mydb`.`All_stories` (`Title_of_a_story`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Name_in_short`
    FOREIGN KEY (`Main_hero`)
    REFERENCES `mydb`.`Main_heroes` (`MHName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Novels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Novels` ;

 CREATE TABLE IF NOT EXISTS `mydb`.`Novels` (
  `Title` VARCHAR(20) NOT NULL,
  `Year` INT(10) NOT NULL,
  `Main_hero` VARCHAR(20) NOT NULL,
  `Side_hero` VARCHAR(20) NULL,
  `Main_series` VARCHAR(50) NULL,
  `Side_series` VARCHAR(45) NULL,
  `Place` VARCHAR(20) NOT NULL,
  `Satire` VARCHAR(50) NOT NULL,
  INDEX `Title_of_a_story_idx` (`Title` ASC) VISIBLE,
  INDEX `Name_idx` (`Main_hero` ASC) VISIBLE,
  INDEX `Name_idx1` (`Side_hero` ASC) VISIBLE,
  INDEX `Title_of_a_series_idx` (`Main_series` ASC) VISIBLE,
  INDEX `Name_idx2` (`Place` ASC) VISIBLE,
  CONSTRAINT `Title_of_a_story`
    FOREIGN KEY (`Title`)
    REFERENCES `mydb`.`All_stories` (`Title_of_a_story`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Name`
    FOREIGN KEY (`Main_hero`)
    REFERENCES `mydb`.`Main_heroes` (`MHName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Name_of_side_hero`
    FOREIGN KEY (`Side_hero`)
    REFERENCES `mydb`.`Side_heroes` (`SHName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Title_of_a_series`
    FOREIGN KEY (`Main_series`)
    REFERENCES `mydb`.`Main_Series` (`Title_of_a_main_series`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Title_of_a_side_series`
    FOREIGN KEY (`Side_series`)
    REFERENCES `mydb`.`Side_Series` (`Title_of_a_side_series`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Name_of_place`
    FOREIGN KEY (`Place`)
    REFERENCES `mydb`.`Places` (`PName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

